# -*- coding: utf-8 -*-
"""[FIX]RecomSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPmfGa9v7tNsNZ3RiCp_-lW3ndxpE5Xa
"""

import pandas as pd
from scipy import sparse

#from google.colab import drive
#drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/

ratings = pd.read_csv('dataset.csv')
print(ratings.shape)
ratings.head()

userRatings = ratings.pivot_table(index=['User_id'],columns=['Nama_wisata'],values='Rating')
userRatings.head()

print("Before: ",userRatings.shape)
userRatings = userRatings.dropna(thresh=10).fillna(0)
#userRatings.fillna(0, inplace=True)
print("After: ",userRatings.shape)

corrMatrix = userRatings.corr(method='spearman')
corrMatrix.head(100)

def get_similar(Genre,Rating):
    similar_ratings = corrMatrix[Genre]*(Rating-2.5)
    similar_ratings = similar_ratings.sort_values(ascending=False)
    #print(type(similar_ratings))
    return similar_ratings

"""# Input 1 Tempat Wisata & Rating-nya"""

wisata = get_similar("tanjung bira",5)

wisata[1:4]

"""# Input Lebih Dari 1:"""

budaya_lover = [("wisata londa",5),("masjid 99 kubah",3),("pantai galesong",1),("tanjung bira",2)]
similar_Nama_wisata = pd.DataFrame()
for Nama_wisata,Rating in budaya_lover:
    similar_Nama_wisata = similar_Nama_wisata.append(get_similar(Nama_wisata,Rating),ignore_index = True)

similar_Nama_wisata.head(3)

similar_Nama_wisata.sum().sort_values(ascending=False).head(3)

alam_lover = [("tanjung bira",5),("pantai galesong",4),("benteng rotterdam",2),("pantai losari",4)]
similar_Nama_wisata = pd.DataFrame()
for Nama_wisata,Rating in alam_lover:
    similar_Nama_wisata = similar_Nama_wisata.append(get_similar(Nama_wisata,Rating),ignore_index = True)

similar_Nama_wisata.head(2)

similar_Nama_wisata.sum().sort_values(ascending=False).head(3)

